services:
  weblate:
    build: .
    image: weblate-oca
    ports:
      - 127.0.0.1:8001:8080
    volumes:
      - ./data/weblate:/app/data
      - ./cache/weblate:/app/cache
    env_file:
      - ./environment
    depends_on:
      - cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    read_only: true
    tmpfs:
      - /run
      - /tmp
  cache:
    image: valkey/valkey:9.0.1
    volumes:
      - ./data/redis:/data
    command: [valkey-server, --save, "60", "1", --loglevel, warning]
    restart: always
    read_only: true
