#!/opt/oca-maintainer-tools/bin/python
import subprocess

from tools.config import is_main_branch
from tools.oca_projects import get_repositories_and_branches


def branch_filter(branch):
    return is_main_branch(branch) and branch not in ("6.1", "7.0", "8.0", "9.0", "10.0")


for repo, branch in get_repositories_and_branches(branch_filter=branch_filter):
    subprocess.check_call([
        '/app/venv/bin/wocg-create-project',
        '--repository', 'https://github.com/OCA/' + repo,
        '--branch', branch,
        '--tmpl-component-slug', '0-oca-project-template-addon',
    ])

subprocess.check_call([
    '/app/venv/bin/wocg-create-components',
])
